//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : PV_ProyectoFinal
	/// Data Source    : DESKTOP-C7O42T2\SQLEXPRESS
	/// Server Version : 14.00.1000
	/// </summary>
	public partial class PvProyectoFinalDB : LinqToDB.Data.DataConnection
	{
		public ITable<Bitacora>    Bitacoras    { get { return this.GetTable<Bitacora>(); } }
		public ITable<Habitacion>  Habitacions  { get { return this.GetTable<Habitacion>(); } }
		public ITable<Hotel>       Hotels       { get { return this.GetTable<Hotel>(); } }
		public ITable<Persona>     Personas     { get { return this.GetTable<Persona>(); } }
		public ITable<Reservacion> Reservacions { get { return this.GetTable<Reservacion>(); } }

		public PvProyectoFinalDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PvProyectoFinalDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PvProyectoFinalDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PvProyectoFinalDB(DataOptions<PvProyectoFinalDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Bitacora")]
	public partial class Bitacora
	{
		[Column("idBitacora"),      PrimaryKey, Identity] public int      IdBitacora      { get; set; } // int
		[Column("idReservacion"),   NotNull             ] public int      IdReservacion   { get; set; } // int
		[Column("idPersona"),       NotNull             ] public int      IdPersona       { get; set; } // int
		[Column("accionRealizada"), NotNull             ] public string   AccionRealizada { get; set; } // varchar(25)
		[Column("fechaDeLaAccion"), NotNull             ] public DateTime FechaDeLaAccion { get; set; } // datetime

		#region Associations

		/// <summary>
		/// FK_Bitacora_Persona (dbo.Persona)
		/// </summary>
		[Association(ThisKey="IdPersona", OtherKey="IdPersona", CanBeNull=false)]
		public Persona Persona { get; set; }

		/// <summary>
		/// FK_Bitacora_Reservacion (dbo.Reservacion)
		/// </summary>
		[Association(ThisKey="IdReservacion", OtherKey="IdReservacion", CanBeNull=false)]
		public Reservacion Reservacion { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Habitacion")]
	public partial class Habitacion
	{
		[Column("idHabitacion"),     PrimaryKey, Identity] public int    IdHabitacion     { get; set; } // int
		[Column("idHotel"),          NotNull             ] public int    IdHotel          { get; set; } // int
		[Column("numeroHabitacion"), NotNull             ] public string NumeroHabitacion { get; set; } // varchar(10)
		[Column("capacidadMaxima"),  NotNull             ] public int    CapacidadMaxima  { get; set; } // int
		[Column("descripcion"),      NotNull             ] public string Descripcion      { get; set; } // varchar(500)
		[Column("estado"),           NotNull             ] public char   Estado           { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Habitacion_Hotel (dbo.Hotel)
		/// </summary>
		[Association(ThisKey="IdHotel", OtherKey="IdHotel", CanBeNull=false)]
		public Hotel Hotel { get; set; }

		/// <summary>
		/// FK_Reservacion_Habitacion_BackReference (dbo.Reservacion)
		/// </summary>
		[Association(ThisKey="IdHabitacion", OtherKey="IdHabitacion", CanBeNull=true)]
		public IEnumerable<Reservacion> Reservacions { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Hotel")]
	public partial class Hotel
	{
		[Column("idHotel"),            PrimaryKey,  Identity] public int     IdHotel            { get; set; } // int
		[Column("nombre"),             NotNull              ] public string  Nombre             { get; set; } // varchar(150)
		[Column("direccion"),             Nullable          ] public string  Direccion          { get; set; } // varchar(500)
		[Column("costoPorCadaAdulto"), NotNull              ] public decimal CostoPorCadaAdulto { get; set; } // numeric(10, 2)
		[Column("costoPorCadaNinho"),  NotNull              ] public decimal CostoPorCadaNinho  { get; set; } // numeric(10, 2)

		#region Associations

		/// <summary>
		/// FK_Habitacion_Hotel_BackReference (dbo.Habitacion)
		/// </summary>
		[Association(ThisKey="IdHotel", OtherKey="IdHotel", CanBeNull=true)]
		public IEnumerable<Habitacion> Habitacions { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Persona")]
	public partial class Persona
	{
		[Column("idPersona"),      PrimaryKey, Identity] public int    IdPersona      { get; set; } // int
		[Column("nombreCompleto"), NotNull             ] public string NombreCompleto { get; set; } // varchar(250)
		[Column("email"),          NotNull             ] public string Email          { get; set; } // varchar(150)
		[Column("clave"),          NotNull             ] public string Clave          { get; set; } // varchar(15)
		[Column("esEmpleado"),     NotNull             ] public bool   EsEmpleado     { get; set; } // bit
		[Column("estado"),         NotNull             ] public char   Estado         { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Bitacora_Persona_BackReference (dbo.Bitacora)
		/// </summary>
		[Association(ThisKey="IdPersona", OtherKey="IdPersona", CanBeNull=true)]
		public IEnumerable<Bitacora> Bitacoras { get; set; }

		/// <summary>
		/// FK_Reservacion_Persona_BackReference (dbo.Reservacion)
		/// </summary>
		[Association(ThisKey="IdPersona", OtherKey="IdPersona", CanBeNull=true)]
		public IEnumerable<Reservacion> Reservacions { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="Reservacion")]
	public partial class Reservacion
	{
		[Column("idReservacion"),        PrimaryKey,  Identity] public int       IdReservacion        { get; set; } // int
		[Column("idPersona"),            NotNull              ] public int       IdPersona            { get; set; } // int
		[Column("idHabitacion"),         NotNull              ] public int       IdHabitacion         { get; set; } // int
		[Column("fechaEntrada"),         NotNull              ] public DateTime  FechaEntrada         { get; set; } // datetime
		[Column("fechaSalida"),          NotNull              ] public DateTime  FechaSalida          { get; set; } // datetime
		[Column("numeroAdultos"),        NotNull              ] public int       NumeroAdultos        { get; set; } // int
		[Column("numeroNinhos"),         NotNull              ] public int       NumeroNinhos         { get; set; } // int
		[Column("totalDiasReservacion"), NotNull              ] public int       TotalDiasReservacion { get; set; } // int
		[Column("costoPorCadaAdulto"),   NotNull              ] public decimal   CostoPorCadaAdulto   { get; set; } // numeric(10, 2)
		[Column("costoPorCadaNinho"),    NotNull              ] public decimal   CostoPorCadaNinho    { get; set; } // numeric(10, 2)
		[Column("costoTotal"),           NotNull              ] public decimal   CostoTotal           { get; set; } // numeric(14, 2)
		[Column("fechaCreacion"),        NotNull              ] public DateTime  FechaCreacion        { get; set; } // datetime
		[Column("fechaModificacion"),       Nullable          ] public DateTime? FechaModificacion    { get; set; } // datetime
		[Column("estado"),               NotNull              ] public char      Estado               { get; set; } // varchar(1)

		#region Associations

		/// <summary>
		/// FK_Bitacora_Reservacion_BackReference (dbo.Bitacora)
		/// </summary>
		[Association(ThisKey="IdReservacion", OtherKey="IdReservacion", CanBeNull=true)]
		public IEnumerable<Bitacora> Bitacoras { get; set; }

		/// <summary>
		/// FK_Reservacion_Habitacion (dbo.Habitacion)
		/// </summary>
		[Association(ThisKey="IdHabitacion", OtherKey="IdHabitacion", CanBeNull=false)]
		public Habitacion Habitacion { get; set; }

		/// <summary>
		/// FK_Reservacion_Persona (dbo.Persona)
		/// </summary>
		[Association(ThisKey="IdPersona", OtherKey="IdPersona", CanBeNull=false)]
		public Persona Persona { get; set; }

		#endregion
	}

	public static partial class PvProyectoFinalDBStoredProcedures
	{
		#region SpAlterdiagram

		public static int SpAlterdiagram(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId, int? @version, byte[] @definition)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32),
				new DataParameter("@version",     @version,     LinqToDB.DataType.Int32),
				new DataParameter("@definition",  @definition,  LinqToDB.DataType.VarBinary)
				{
					Size = -1
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_alterdiagram]", parameters);
		}

		#endregion

		#region SpCancelarReservacion

		public static IEnumerable<SpCancelarReservacionResult> SpCancelarReservacion(this PvProyectoFinalDB dataConnection, int? @idReservacion, int? @idPersona)
		{
			var parameters = new []
			{
				new DataParameter("@idReservacion", @idReservacion, LinqToDB.DataType.Int32),
				new DataParameter("@idPersona",     @idPersona,     LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpCancelarReservacionResult>("[dbo].[sp_CancelarReservacion]", parameters);
		}

		public partial class SpCancelarReservacionResult
		{
			[Column("mensaje")] public string Mensaje { get; set; }
		}

		#endregion

		#region SpConsultarDisponibilidadHabitaciones

		public static IEnumerable<SpConsultarDisponibilidadHabitacionesResult> SpConsultarDisponibilidadHabitaciones(this PvProyectoFinalDB dataConnection, int? @idHotel, int? @numeroAdultos, int? @numeroNinhos)
		{
			var parameters = new []
			{
				new DataParameter("@idHotel",       @idHotel,       LinqToDB.DataType.Int32),
				new DataParameter("@numeroAdultos", @numeroAdultos, LinqToDB.DataType.Int32),
				new DataParameter("@numeroNinhos",  @numeroNinhos,  LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpConsultarDisponibilidadHabitacionesResult>("[dbo].[sp_ConsultarDisponibilidadHabitaciones]", parameters);
		}

		public partial class SpConsultarDisponibilidadHabitacionesResult
		{
			[Column("idHabitacion")   ] public int IdHabitacion    { get; set; }
			[Column("capacidadMaxima")] public int CapacidadMaxima { get; set; }
		}

		#endregion

		#region SpConsultarReservacionesCliente

		public static IEnumerable<SpConsultarReservacionesClienteResult> SpConsultarReservacionesCliente(this PvProyectoFinalDB dataConnection, int? @idPersona)
		{
			var parameters = new []
			{
				new DataParameter("@idPersona", @idPersona, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpConsultarReservacionesClienteResult>("[dbo].[sp_ConsultarReservacionesCliente]", parameters);
		}

		public partial class SpConsultarReservacionesClienteResult
		{
			[Column("idReservacion")     ] public int      IdReservacion      { get; set; }
			                               public string   Cliente            { get; set; }
			                               public string   Hotel              { get; set; }
			[Column("fechaEntrada")      ] public DateTime FechaEntrada       { get; set; }
			[Column("fechaSalida")       ] public DateTime FechaSalida        { get; set; }
			[Column("numeroAdultos")     ] public int      NumeroAdultos      { get; set; }
			[Column("numeroNinhos")      ] public int      NumeroNinhos       { get; set; }
			[Column("costoPorCadaAdulto")] public decimal  CostoPorCadaAdulto { get; set; }
			[Column("costoPorCadaNinho") ] public decimal  CostoPorCadaNinho  { get; set; }
			[Column("costoTotal")        ] public decimal  CostoTotal         { get; set; }
			                               public string   Estado             { get; set; }
		}

		#endregion

		#region SpConsultarReservacionesEmpleado

		public static IEnumerable<SpConsultarReservacionesEmpleadoResult> SpConsultarReservacionesEmpleado(this PvProyectoFinalDB dataConnection, int? @idPersona, string @nombreCliente, DateTime? @fechaEntrada, DateTime? @fechaSalida)
		{
			var parameters = new []
			{
				new DataParameter("@idPersona",     @idPersona,     LinqToDB.DataType.Int32),
				new DataParameter("@nombreCliente", @nombreCliente, LinqToDB.DataType.NVarChar)
				{
					Size = 100
				},
				new DataParameter("@fechaEntrada",  @fechaEntrada,  LinqToDB.DataType.Date),
				new DataParameter("@fechaSalida",   @fechaSalida,   LinqToDB.DataType.Date)
			};

			return dataConnection.QueryProc<SpConsultarReservacionesEmpleadoResult>("[dbo].[sp_ConsultarReservacionesEmpleado]", parameters);
		}

		public partial class SpConsultarReservacionesEmpleadoResult
		{
			public int      Id                { get; set; }
			public string   NombreUsuario     { get; set; }
			public string   Correo            { get; set; }
			public DateTime FechaEntrada      { get; set; }
			public DateTime FechaSalida       { get; set; }
			public string   NombreHotel       { get; set; }
			public string   NumeroHabitacion  { get; set; }
			public decimal  CostoTotal        { get; set; }
			public string   EstadoReservacion { get; set; }
		}

		#endregion

		#region SpCrearHabitacion

		public static IEnumerable<SpCrearHabitacionResult> SpCrearHabitacion(this PvProyectoFinalDB dataConnection, int? @idHotel, string @numeroHabitacion, int? @capacidadMaxima, string @descripcion)
		{
			var parameters = new []
			{
				new DataParameter("@idHotel",          @idHotel,          LinqToDB.DataType.Int32),
				new DataParameter("@numeroHabitacion", @numeroHabitacion, LinqToDB.DataType.VarChar)
				{
					Size = 10
				},
				new DataParameter("@capacidadMaxima",  @capacidadMaxima,  LinqToDB.DataType.Int32),
				new DataParameter("@descripcion",      @descripcion,      LinqToDB.DataType.VarChar)
				{
					Size = 500
				}
			};

			return dataConnection.QueryProc<SpCrearHabitacionResult>("[dbo].[sp_CrearHabitacion]", parameters);
		}

		public partial class SpCrearHabitacionResult
		{
			[Column("mensaje")] public string Mensaje { get; set; }
		}

		#endregion

		#region SpCrearReservacion

		public static IEnumerable<SpCrearReservacionResult> SpCrearReservacion(this PvProyectoFinalDB dataConnection, int? @idHotel, int? @idPersona, int? @idHabitacion, DateTime? @fechaEntrada, DateTime? @fechaSalida, int? @numeroAdultos, int? @numeroNinhos, decimal? @costoPorCadaAdulto, decimal? @costoPorCadaNinho, int? @totalDiasReservacion, decimal? @costoTotal)
		{
			var parameters = new []
			{
				new DataParameter("@idHotel",              @idHotel,              LinqToDB.DataType.Int32),
				new DataParameter("@idPersona",            @idPersona,            LinqToDB.DataType.Int32),
				new DataParameter("@idHabitacion",         @idHabitacion,         LinqToDB.DataType.Int32),
				new DataParameter("@fechaEntrada",         @fechaEntrada,         LinqToDB.DataType.Date),
				new DataParameter("@fechaSalida",          @fechaSalida,          LinqToDB.DataType.Date),
				new DataParameter("@numeroAdultos",        @numeroAdultos,        LinqToDB.DataType.Int32),
				new DataParameter("@numeroNinhos",         @numeroNinhos,         LinqToDB.DataType.Int32),
				new DataParameter("@costoPorCadaAdulto",   @costoPorCadaAdulto,   LinqToDB.DataType.Decimal),
				new DataParameter("@costoPorCadaNinho",    @costoPorCadaNinho,    LinqToDB.DataType.Decimal),
				new DataParameter("@totalDiasReservacion", @totalDiasReservacion, LinqToDB.DataType.Int32),
				new DataParameter("@costoTotal",           @costoTotal,           LinqToDB.DataType.Decimal)
			};

			return dataConnection.QueryProc<SpCrearReservacionResult>("[dbo].[sp_CrearReservacion]", parameters);
		}

		public partial class SpCrearReservacionResult
		{
			[Column("idReservacion")] public int? IdReservacion { get; set; }
		}

		#endregion

		#region SpCreatediagram

		public static int SpCreatediagram(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId, int? @version, byte[] @definition)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32),
				new DataParameter("@version",     @version,     LinqToDB.DataType.Int32),
				new DataParameter("@definition",  @definition,  LinqToDB.DataType.VarBinary)
				{
					Size = -1
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_creatediagram]", parameters);
		}

		#endregion

		#region SpDropdiagram

		public static int SpDropdiagram(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[sp_dropdiagram]", parameters);
		}

		#endregion

		#region SpEditarHabitacion

		public static IEnumerable<SpEditarHabitacionResult> SpEditarHabitacion(this PvProyectoFinalDB dataConnection, int? @idHabitacion, string @numeroHabitacion, int? @capacidadMaxima, string @descripcion)
		{
			var parameters = new []
			{
				new DataParameter("@idHabitacion",     @idHabitacion,     LinqToDB.DataType.Int32),
				new DataParameter("@numeroHabitacion", @numeroHabitacion, LinqToDB.DataType.VarChar)
				{
					Size = 10
				},
				new DataParameter("@capacidadMaxima",  @capacidadMaxima,  LinqToDB.DataType.Int32),
				new DataParameter("@descripcion",      @descripcion,      LinqToDB.DataType.VarChar)
				{
					Size = 500
				}
			};

			return dataConnection.QueryProc<SpEditarHabitacionResult>("[dbo].[sp_EditarHabitacion]", parameters);
		}

		public partial class SpEditarHabitacionResult
		{
			[Column("mensaje")] public string Mensaje { get; set; }
		}

		#endregion

		#region SpGestionarReservacionesEmpleado

		public static IEnumerable<SpGestionarReservacionesEmpleadoResult> SpGestionarReservacionesEmpleado(this PvProyectoFinalDB dataConnection, int? @idPersona, string @nombreCliente, DateTime? @fechaEntrada, DateTime? @fechaSalida)
		{
			var parameters = new []
			{
				new DataParameter("@idPersona",     @idPersona,     LinqToDB.DataType.Int32),
				new DataParameter("@nombreCliente", @nombreCliente, LinqToDB.DataType.VarChar)
				{
					Size = 150
				},
				new DataParameter("@fechaEntrada",  @fechaEntrada,  LinqToDB.DataType.Date),
				new DataParameter("@fechaSalida",   @fechaSalida,   LinqToDB.DataType.Date)
			};

			return dataConnection.QueryProc<SpGestionarReservacionesEmpleadoResult>("[dbo].[sp_GestionarReservacionesEmpleado]", parameters);
		}

		public partial class SpGestionarReservacionesEmpleadoResult
		{
			[Column("idReservacion")     ] public int      IdReservacion      { get; set; }
			                               public string   Cliente            { get; set; }
			                               public string   Hotel              { get; set; }
			[Column("fechaEntrada")      ] public DateTime FechaEntrada       { get; set; }
			[Column("fechaSalida")       ] public DateTime FechaSalida        { get; set; }
			[Column("numeroAdultos")     ] public int      NumeroAdultos      { get; set; }
			[Column("numeroNinhos")      ] public int      NumeroNinhos       { get; set; }
			[Column("costoPorCadaAdulto")] public decimal  CostoPorCadaAdulto { get; set; }
			[Column("costoPorCadaNinho") ] public decimal  CostoPorCadaNinho  { get; set; }
			[Column("costoTotal")        ] public decimal  CostoTotal         { get; set; }
			                               public string   Estado             { get; set; }
		}

		#endregion

		#region SpHelpdiagramdefinition

		public static IEnumerable<SpHelpdiagramdefinitionResult> SpHelpdiagramdefinition(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpHelpdiagramdefinitionResult>("[dbo].[sp_helpdiagramdefinition]", parameters);
		}

		public partial class SpHelpdiagramdefinitionResult
		{
			[Column("version")   ] public int?   Version    { get; set; }
			[Column("definition")] public byte[] Definition { get; set; }
		}

		#endregion

		#region SpHelpdiagrams

		public static IEnumerable<SpHelpdiagramsResult> SpHelpdiagrams(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",    @ownerId,     LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpHelpdiagramsResult>("[dbo].[sp_helpdiagrams]", parameters);
		}

		public partial class SpHelpdiagramsResult
		{
			public string Database { get; set; }
			public string Name     { get; set; }
			public int    ID       { get; set; }
			public string Owner    { get; set; }
			public int    OwnerID  { get; set; }
		}

		#endregion

		#region SpInactivaHabitacion

		public static IEnumerable<SpInactivaHabitacionResult> SpInactivaHabitacion(this PvProyectoFinalDB dataConnection, int? @idHabitacion)
		{
			var parameters = new []
			{
				new DataParameter("@idHabitacion", @idHabitacion, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpInactivaHabitacionResult>("[dbo].[sp_InactivaHabitacion]", parameters);
		}

		public partial class SpInactivaHabitacionResult
		{
			[Column("mensaje")] public string Mensaje { get; set; }
		}

		#endregion

		#region SpLoginUsuario

		public static IEnumerable<SpLoginUsuarioResult> SpLoginUsuario(this PvProyectoFinalDB dataConnection, string @email, string @clave)
		{
			var parameters = new []
			{
				new DataParameter("@email", @email, LinqToDB.DataType.VarChar)
				{
					Size = 150
				},
				new DataParameter("@clave", @clave, LinqToDB.DataType.VarChar)
				{
					Size = 15
				}
			};

			return dataConnection.QueryProc<SpLoginUsuarioResult>("[dbo].[sp_LoginUsuario]", parameters);
		}

		public partial class SpLoginUsuarioResult
		{
			[Column("idPersona")     ] public int?   IdPersona      { get; set; }
			[Column("nombreCompleto")] public string NombreCompleto { get; set; }
			[Column("esEmpleado")    ] public bool?  EsEmpleado     { get; set; }
		}

		#endregion

		#region SpModificarReservacion

		public static IEnumerable<SpModificarReservacionResult> SpModificarReservacion(this PvProyectoFinalDB dataConnection, int? @idReservacion, DateTime? @fechaEntrada, DateTime? @fechaSalida, int? @numeroAdultos, int? @numeroNinhos, int? @idHabitacion, decimal? @costoPorCadaAdulto, decimal? @costoPorCadaNinho, int? @totalDiasReservacion, decimal? @costoTotal, int? @idPersona)
		{
			var parameters = new []
			{
				new DataParameter("@idReservacion",        @idReservacion,        LinqToDB.DataType.Int32),
				new DataParameter("@fechaEntrada",         @fechaEntrada,         LinqToDB.DataType.Date),
				new DataParameter("@fechaSalida",          @fechaSalida,          LinqToDB.DataType.Date),
				new DataParameter("@numeroAdultos",        @numeroAdultos,        LinqToDB.DataType.Int32),
				new DataParameter("@numeroNinhos",         @numeroNinhos,         LinqToDB.DataType.Int32),
				new DataParameter("@idHabitacion",         @idHabitacion,         LinqToDB.DataType.Int32),
				new DataParameter("@costoPorCadaAdulto",   @costoPorCadaAdulto,   LinqToDB.DataType.Decimal),
				new DataParameter("@costoPorCadaNinho",    @costoPorCadaNinho,    LinqToDB.DataType.Decimal),
				new DataParameter("@totalDiasReservacion", @totalDiasReservacion, LinqToDB.DataType.Int32),
				new DataParameter("@costoTotal",           @costoTotal,           LinqToDB.DataType.Decimal),
				new DataParameter("@idPersona",            @idPersona,            LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpModificarReservacionResult>("[dbo].[sp_ModificarReservacion]", parameters);
		}

		public partial class SpModificarReservacionResult
		{
			public string Mensaje { get; set; }
		}

		#endregion

		#region SpObtenerMisReservaciones

		public static IEnumerable<SpObtenerMisReservacionesResult> SpObtenerMisReservaciones(this PvProyectoFinalDB dataConnection, int? @IdUsuario)
		{
			var parameters = new []
			{
				new DataParameter("@IdUsuario", @IdUsuario, LinqToDB.DataType.Int32)
			};

			return dataConnection.QueryProc<SpObtenerMisReservacionesResult>("[dbo].[SpObtenerMisReservaciones]", parameters);
		}

		public partial class SpObtenerMisReservacionesResult
		{
			[Column("idReservacion")] public int      IdReservacion { get; set; }
			[Column("fechaEntrada") ] public DateTime FechaEntrada  { get; set; }
			[Column("fechaSalida")  ] public DateTime FechaSalida   { get; set; }
			[Column("costoTotal")   ] public decimal  CostoTotal    { get; set; }
			[Column("estado")       ] public char     Estado        { get; set; }
			                          public string   NombreUsuario { get; set; }
			                          public string   NombreHotel   { get; set; }
			                          public string   EstadoVisual  { get; set; }
		}

		#endregion

		#region SpObtenerReservacionesConUsuario

		public static IEnumerable<SpObtenerReservacionesConUsuarioResult> SpObtenerReservacionesConUsuario(this PvProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpObtenerReservacionesConUsuarioResult>("[dbo].[SpObtenerReservacionesConUsuario]");
		}

		public partial class SpObtenerReservacionesConUsuarioResult
		{
			public int      Id                { get; set; }
			public string   NombreUsuario     { get; set; }
			public string   Correo            { get; set; }
			public DateTime FechaEntrada      { get; set; }
			public DateTime FechaSalida       { get; set; }
			public string   NombreHotel       { get; set; }
			public string   NumeroHabitacion  { get; set; }
			public decimal  CostoTotal        { get; set; }
			public string   EstadoReservacion { get; set; }
		}

		#endregion

		#region SpRenamediagram

		public static int SpRenamediagram(this PvProyectoFinalDB dataConnection, string @diagramname, int? @ownerId, string @newDiagramname)
		{
			var parameters = new []
			{
				new DataParameter("@diagramname",     @diagramname,    LinqToDB.DataType.NVarChar)
				{
					Size = 128
				},
				new DataParameter("@owner_id",        @ownerId,        LinqToDB.DataType.Int32),
				new DataParameter("@new_diagramname", @newDiagramname, LinqToDB.DataType.NVarChar)
				{
					Size = 128
				}
			};

			return dataConnection.ExecuteProc("[dbo].[sp_renamediagram]", parameters);
		}

		#endregion

		#region SpUpgraddiagrams

		public static int SpUpgraddiagrams(this PvProyectoFinalDB dataConnection)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_upgraddiagrams]");
		}

		#endregion

		#region SpValidarDisponibilidadHabitacion

		public static int SpValidarDisponibilidadHabitacion(this PvProyectoFinalDB dataConnection, int? @idHabitacion, int? @numeroAdultos, int? @numeroNinhos)
		{
			var parameters = new []
			{
				new DataParameter("@idHabitacion",  @idHabitacion,  LinqToDB.DataType.Int32),
				new DataParameter("@numeroAdultos", @numeroAdultos, LinqToDB.DataType.Int32),
				new DataParameter("@numeroNinhos",  @numeroNinhos,  LinqToDB.DataType.Int32)
			};

			return dataConnection.ExecuteProc("[dbo].[sp_ValidarDisponibilidadHabitacion]", parameters);
		}

		#endregion

		#region SpVerClientesActivos

		public static IEnumerable<SpVerClientesActivosResult> SpVerClientesActivos(this PvProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpVerClientesActivosResult>("[dbo].[sp_VerClientesActivos]");
		}

		public partial class SpVerClientesActivosResult
		{
			[Column("idPersona")     ] public int    IdPersona      { get; set; }
			[Column("nombreCompleto")] public string NombreCompleto { get; set; }
		}

		#endregion

		#region SpVerHabitaciones

		public static IEnumerable<SpVerHabitacionesResult> SpVerHabitaciones(this PvProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpVerHabitacionesResult>("[dbo].[sp_VerHabitaciones]");
		}

		public partial class SpVerHabitacionesResult
		{
			[Column("idHabitacion")    ] public int    IdHabitacion     { get; set; }
			[Column("nombre")          ] public string Nombre           { get; set; }
			[Column("numeroHabitacion")] public string NumeroHabitacion { get; set; }
			[Column("capacidadMaxima") ] public int    CapacidadMaxima  { get; set; }
			[Column("estado")          ] public string Estado           { get; set; }
		}

		#endregion

		#region SpVerHoteles

		public static IEnumerable<SpVerHotelesResult> SpVerHoteles(this PvProyectoFinalDB dataConnection)
		{
			return dataConnection.QueryProc<SpVerHotelesResult>("[dbo].[sp_VerHoteles]");
		}

		public partial class SpVerHotelesResult
		{
			[Column("idHotel")] public int    IdHotel { get; set; }
			[Column("nombre") ] public string Nombre  { get; set; }
		}

		#endregion
	}

	public static partial class SqlFunctions
	{
		#region FnDiagramobjects

		[Sql.Function(Name="[dbo].[fn_diagramobjects]", ServerSideOnly=true)]
		public static int? FnDiagramobjects()
		{
			throw new InvalidOperationException();
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Bitacora Find(this ITable<Bitacora> table, int IdBitacora)
		{
			return table.FirstOrDefault(t =>
				t.IdBitacora == IdBitacora);
		}

		public static Habitacion Find(this ITable<Habitacion> table, int IdHabitacion)
		{
			return table.FirstOrDefault(t =>
				t.IdHabitacion == IdHabitacion);
		}

		public static Hotel Find(this ITable<Hotel> table, int IdHotel)
		{
			return table.FirstOrDefault(t =>
				t.IdHotel == IdHotel);
		}

		public static Persona Find(this ITable<Persona> table, int IdPersona)
		{
			return table.FirstOrDefault(t =>
				t.IdPersona == IdPersona);
		}

		public static Reservacion Find(this ITable<Reservacion> table, int IdReservacion)
		{
			return table.FirstOrDefault(t =>
				t.IdReservacion == IdReservacion);
		}
	}
}
